// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum FaciityId : short
{
  None = 0,
  BreakRoom = 1,
  Gloryhole = 2,
  GloryholeW = 3,
};


}
