// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GeneticSkill : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GeneticSkill __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Level { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public fbs.GeneticSkillType GeneticSkillType { get { return (fbs.GeneticSkillType)__p.bb.GetSbyte(__p.bb_pos + 8); } }

  public static Offset<fbs.GeneticSkill> CreateGeneticSkill(FlatBufferBuilder builder, int Id, int Level, fbs.GeneticSkillType GeneticSkillType) {
    builder.Prep(4, 12);
    builder.Pad(3);
    builder.PutSbyte((sbyte)GeneticSkillType);
    builder.PutInt(Level);
    builder.PutInt(Id);
    return new Offset<fbs.GeneticSkill>(builder.Offset);
  }
}


}
