// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum GeneticSkillType : sbyte
{
  Status = 0,
  Buff = 1,
  Debuff = 2,
};


}
