// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Sensitivity : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Sensitivity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Mouth { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Nipple { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int Boobs { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public int Clitris { get { return __p.bb.GetInt(__p.bb_pos + 12); } }
  public int Vagina { get { return __p.bb.GetInt(__p.bb_pos + 16); } }
  public int Anus { get { return __p.bb.GetInt(__p.bb_pos + 20); } }
  public int Penis { get { return __p.bb.GetInt(__p.bb_pos + 24); } }
  public int Scrotum { get { return __p.bb.GetInt(__p.bb_pos + 28); } }
  public int Prostate { get { return __p.bb.GetInt(__p.bb_pos + 32); } }

  public static Offset<fbs.Sensitivity> CreateSensitivity(FlatBufferBuilder builder, int Mouth, int Nipple, int Boobs, int Clitris, int Vagina, int Anus, int Penis, int Scrotum, int Prostate) {
    builder.Prep(4, 36);
    builder.PutInt(Prostate);
    builder.PutInt(Scrotum);
    builder.PutInt(Penis);
    builder.PutInt(Anus);
    builder.PutInt(Vagina);
    builder.PutInt(Clitris);
    builder.PutInt(Boobs);
    builder.PutInt(Nipple);
    builder.PutInt(Mouth);
    return new Offset<fbs.Sensitivity>(builder.Offset);
  }
}


}
