// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum Sex : sbyte
{
  None = 0,
  Male = 1,
  Woman = 2,
  Futanari = 3,
};


}
