// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum Species : sbyte
{
  None = 0,
  Human = 1,
  Beastman = 2,
  Dwarf = 3,
  Elf = 4,
};


}
