// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UUID : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public UUID __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Upper { get { return __p.bb.GetLong(__p.bb_pos + 0); } }
  public long Lower { get { return __p.bb.GetLong(__p.bb_pos + 8); } }

  public static Offset<fbs.UUID> CreateUUID(FlatBufferBuilder builder, long Upper, long Lower) {
    builder.Prep(8, 16);
    builder.PutLong(Lower);
    builder.PutLong(Upper);
    return new Offset<fbs.UUID>(builder.Offset);
  }
}


}
